# The name of this app. Must be unique within a project.
name: "pro_lnclassapp"
# The runtime the application uses.

type: 'ruby:3.0'

dependencies:
    nodejs:
        yarn: "*"

relationships:
    postgresdatabase: 'dbpostgres:postgresql'

disk: 2048

# Set environment variables to adjust how Rails will run.
variables:
    env:
        BUNDLE_CACHE_ALL: '1'
        BUNDLE_CLEAN: '1'
        BUNDLE_DEPLOYMENT: '1'
        BUNDLE_ERROR_ON_STDERR: '1'
        BUNDLE_WITHOUT: 'development:test'
        DEFAULT_BUNDLER_VERSION: "2.3.25" # in case none is mentioned in Gemfile.lock
        EXECJS_RUNTIME: 'Node'
        NODE_ENV: 'production'
        NODE_VERSION: v14.17.6
        NVM_VERSION: v0.38.0
        RACK_ENV: 'production'
        RAILS_ENV: 'production'
        RAILS_LOG_TO_STDOUT: '1'
        RAILS_TMP: '/tmp'
        

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    "/log":
        source: local
        source_path: log
    "/storage":
        source: local
        source_path: storage
    "/tmp":
        source: local
        source_path: tmp

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # The build hook turns what is in source control into the deployable application.
    build: |
        
    # The deploy hook runs after your application has been deployed and started.
    deploy: |
        bundle exec rails db:migrate


# The configuration of the application when running.
web:
    upstream:
        # Send requests to the app server through a unix socket, whose location
        # will be defined in an environment variable named SOCKET.
        socket_family: "unix"
    commands:
        #start: 'bundle exec unicorn'
        start: "bundle exec unicorn -l $SOCKET"
